apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
spec:
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: siddhi2003/weather-app-2:443eee7c3d3860107c609a65e399f4b25e9d6ac1
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
        env:
        - name: PORT
          value: "5173"
---
apiVersion: v1
kind: Service
metadata:
  name: weather
spec:
  selector:
    app: weather
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5173
  type: LoadBalancer