name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - 'release/*'  # Trigger on pushes to the main branch or any branch starting with "release/"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Jinja2
      run: pip install jinja2

    - name: Render Kubernetes manifest from Jinja template
      run: python render_template.py
      env:
       IMAGE_TAG: ${{ github.sha }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile  # Update this if your Dockerfile is in a different location
        push: true
        tags: |
          siddhi2003/weather-app-2:${{ github.sha }}

    - name: Log out from Docker Hub
      run: docker logout
