name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - 'release/*'  # Trigger on pushes to the main branch or any branch starting with "release/"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v5
       IMAGE_TAG=${{ github.sha }}
      with:
        context: .
        file: ./Dockerfile  # Update this if your Dockerfile is in a different location
        push: true
        tags: |
          siddhi2003/weather-app-2:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Log out from Docker Hub
      run: docker logout
